name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:   # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats Images
        uses: anuraghazra/github-readme-stats@master
        with:
          USERNAME: amrkhaledccd # Change this to your actual username

